name: Flutter Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Reconstruct Project Structure
        run: |
          mkdir temp_lib
          cp lib/main.dart temp_lib/
          cp pubspec.yaml temp_pubspec.yaml
          find . -maxdepth 1 ! -name '.git' ! -name 'temp_lib' ! -name 'temp_pubspec.yaml' ! -name '.' -exec rm -rf {} +
          flutter create --org com.maximum.net --project-name maximum_net_app .
          cp temp_lib/main.dart lib/main.dart
          cp temp_pubspec.yaml pubspec.yaml

      - name: Patch Android Manifest
        run: |
          # Патчимо всі маніфести для гарантованого доступу до мережі
          MANIFEST_FILES=$(find android/app/src -name "AndroidManifest.xml")
          for file in $MANIFEST_FILES; do
            sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />' "$file"
            sed -i '/<application/i \    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />' "$file"
            sed -i 's/<application/<application android:usesCleartextTraffic="true"/' "$file"
          done

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MaxNet-App
          path: build/app/outputs/flutter-apk/*-release.apk
